# Generated by Django 5.2.8 on 2025-11-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductName', models.CharField(max_length=100)),
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('Review', models.CharField(max_length=100)),
            ],
        ),
    ]
